import type { Lead, ResultPage, RunProgress, RunStatus } from "../lib/api-types.ts";

export function lead(overrides: Partial<Lead> = {}): Lead {
  return {
    id: "lead_fixture",
    original_shop_type: "Eyewear Brand",
    shop_type: "eyewear",
    generated_query: "site:myshopify.com/products acetate frames",
    query_score: 82.29,
    query_generation_reason: "Concrete product phrase for an independent brand.",
    search_query: "site:myshopify.com/products acetate frames",
    google_rank: 1,
    google_result_url: "https://fixture.myshopify.com/products/frames",
    myshopify_domain: "fixture.myshopify.com",
    final_url: "https://fixture.example/products/frames",
    canonical_url: "https://fixture.example/products/frames",
    resolved_domain: "fixture.example",
    store_name: "Fixture Optics",
    email: "hello@fixture.example",
    email_source_url: "https://fixture.example/pages/contact",
    phone: "+12125550100",
    phone_source_url: "https://fixture.example/pages/contact",
    contact_url: "https://fixture.example/pages/contact",
    social_profiles: ["https://instagram.com/fixture"],
    additional_information: "pages_examined=3",
    shopify_confidence: 100,
    relevance_score: 92,
    lead_score: 90,
    status: "qualified",
    rejection_reason: null,
    error: null,
    business_qualifier: "brand",
    pipeline_version: 2,
    scoring_version: 2,
    store_fit_state: "specialist",
    store_fit_evidence: [{
      intent: {
        originalShopType: "Eyewear Brand",
        shopType: "eyewear",
        businessQualifier: "brand",
        categoryVocabulary: ["eyewear", "acetate frames"],
      },
      accepted: true,
      state: "specialist",
      score: 92,
      matchedTerms: ["eyewear", "acetate frames"],
      sourceUrls: ["https://fixture.example/collections/eyewear"],
      signalKinds: ["category_collection_assortment"],
      breadthEvidence: [],
      evidence: [{
        sourceUrl: "https://fixture.example/collections/eyewear",
        pageType: "collection",
        matchedTerms: ["eyewear", "acetate frames"],
        claimTerms: [],
        signals: ["category_collection_assortment"],
        breadthTerms: [],
        negativeSignals: [],
        strength: 65,
        textLength: 1840,
      }],
      reason: "category_dominant_independent_assortment_signals",
    }],
    contactability_tier: "direct",
    contact_evidence: {
      emails: [{ kind: "email", value: "hello@fixture.example", sourceUrl: "https://fixture.example/pages/contact", method: "mailto", confidence: 96, validationReason: "same_store_contact_page" }],
      phones: [{ kind: "phone", value: "+12125550100", sourceUrl: "https://fixture.example/pages/contact", method: "tel", confidence: 96, validationReason: "same_store_contact_page" }],
      contactPages: [{
        kind: "contact_page",
        value: "https://fixture.example/pages/contact",
        sourceUrl: "https://fixture.example/pages/contact",
        method: "contact_page_decision_v2",
        confidence: 100,
        validationReason: "validated_contact_page",
        decision: {
          accepted: true,
          routeAccepted: true,
          routeReason: "contact_route",
          sameStore: true,
          httpUsable: true,
          pageUsable: true,
          positiveSignals: ["contact_form"],
          validationReason: "validated_contact_page",
          sourceUrl: "https://fixture.example/pages/contact",
        },
      }],
      socialProfiles: [{ kind: "social_profile", value: "https://instagram.com/fixture", sourceUrl: "https://fixture.example/", method: "associated_link_instagram", confidence: 86, validationReason: "store_owned_layout_link" }],
      organizationNames: [{ kind: "organization_name", value: "Fixture Optics", sourceUrl: "https://fixture.example/", method: "site_metadata", confidence: 86, validationReason: "site_name_metadata" }],
    },
    identity_confidence: 100,
    identity_evidence: {
      stableHostname: "fixture.myshopify.com",
      displayHostname: "fixture.example",
      observedHostnames: ["fixture.myshopify.com", "fixture.example"],
      mergedOccurrenceCount: 1,
      canonical: {
        url: "https://fixture.example/products/frames",
        hostname: "fixture.example",
        trusted: true,
        reason: "canonical_matches_observed_host",
      },
      method: "observed_myshopify_host",
      confidence: 100,
    },
    score_breakdown: {
      version: 2,
      components: { identity: 20, shopifyValidation: 25, categoryFit: 30, contactEvidence: 15 },
      total: 90,
      semantics: "deterministic_evidence_rank_not_probability",
    },
    discovery_occurrences: [{
      categoryIntent: { originalShopType: "Eyewear Brand", shopType: "eyewear", businessQualifier: "brand", categoryVocabulary: ["eyewear"] },
      originalShopType: "Eyewear Brand",
      shopType: "eyewear",
      businessQualifier: "brand",
      query: "site:myshopify.com/products acetate frames",
      queryScore: 82.29,
      queryGenerationReason: "Concrete product phrase for an independent brand.",
      querySourceUrls: ["https://research.example/eyewear"],
      categoryVocabulary: ["eyewear", "acetate frames"],
      rank: 1,
      resultUrl: "https://fixture.myshopify.com/products/frames",
      finalUrl: "https://fixture.example/products/frames",
      resolvedDomain: "fixture.example",
      myshopifyDomain: "fixture.myshopify.com",
    }],
    matched_categories: [{ originalShopType: "Eyewear Brand", shopType: "eyewear", businessQualifier: "brand", categoryVocabulary: ["eyewear"] }],
    score_semantics: "evidence_rank_v2",
    ...overrides,
  };
}

export const progress: RunProgress = {
  shopTypesTotal: 1, shopTypesProcessed: 1, blankShopTypesSkipped: 0,
  invalidShopTypes: 0, queryCandidatesGenerated: 1, queryCandidatesValidated: 1,
  queryCandidatesProbed: 1, queriesSelected: 1, planningWarnings: 0,
  queriesTotal: 1, queriesProcessed: 1, storesDiscovered: 1,
  storesQualified: 1, storesRejected: 0, failures: 0, queryFailures: 0,
  occurrenceFailures: 0, storeProcessingFailures: 0, outputRows: 1,
};

export function runStatus(overrides: Partial<RunStatus> = {}): RunStatus {
  return {
    runId: "run_abcdefghijklmnop",
    state: "completed",
    phase: "finished",
    stage: "completed",
    createdAt: "2026-08-01T00:00:00.000Z",
    startedAt: "2026-08-01T00:00:01.000Z",
    completedAt: "2026-08-01T00:00:02.000Z",
    progress,
    resultsAvailable: true,
    pipelineVersion: 2,
    scoringVersion: 2,
    queryReview: null,
    error: null,
    ...overrides,
  };
}

export function resultPage(items: Lead[] = [lead()]): ResultPage {
  return {
    runId: "run_abcdefghijklmnop",
    summary: {
      total: items.length,
      qualified: items.filter(({ status }) => status === "qualified").length,
      rejected: items.filter(({ status }) => status === "rejected").length,
      failed: items.filter(({ status }) => status === "failed").length,
    },
    pagination: { page: 1, pageSize: 25, totalItems: items.length, totalPages: items.length ? 1 : 0 },
    items,
  };
}
